#ifndef ADHOCUTIL_UNIQUE_H
#define ADHOCUTIL_UNIQUE_H

#define CONCATENATE_DETAIL(x, y) x##y
#define CONCATENATE(x, y) CONCATENATE_DETAIL(x, y)
#define MAKE_UNIQUE(x) CONCATENATE(x, __COUNTER__)

#endif
